name: Release Nginx Build

on:
  push:
    tags:
      - 'v*' # 当推送带v开头的tag时触发

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        debian_version: ['trixie', 'bookworm', 'bullseye']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare variables
        id: vars
        run: |
          TAG=${{ github.ref_name }}
          NGINX_VERSION=${TAG#v}
          echo "NGINX_VERSION=${NGINX_VERSION}" >> $GITHUB_ENV
          echo "DEBIAN_VERSION=${{ matrix.debian_version }}" >> $GITHUB_ENV

      - name: Build Nginx
        run: |
          echo "Building Nginx version ${{ env.NGINX_VERSION }} for Debian ${{ env.DEBIAN_VERSION }}"
          docker compose build
          docker compose run --rm nginx-builder

      - name: Package artifact
        run: |
          tar -czf nginx-${{ env.NGINX_VERSION }}-debian-${{ env.DEBIAN_VERSION }}.tar.gz -C output .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-build-${{ matrix.debian_version }}
          path: nginx-*.tar.gz

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*/*.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true